from monthlyStatistics import MonthlyStatistics
from rankingModel import RankingModel

############################################################################
# fund_statistics, benchmark_statistics = MonthlyStatistics().statistics()
# print(fund_statistics)
# print(benchmark_statistics)
############################################################################
# df_AvgReturn, df_MedianReturn, df_MaxReturn, df_MinReturn, df_StDev, df_Variance, df_Beta, df_DownsideDev, df_Skew, df_Kurtosis, df_Kurt_Skew, df_ExcessKurtosis, df_ExcessKurtosis_Skew, df_CompoundedReturn, df_CAGR, df_MaxDD, df_MarkowitzReturnFunction, df_MarkowitzReturnFunction_CAGR, df_AvgReturn_StDev, df_MedianReturn_StDev, df_CAGR_StDev, df_AvgReturn_MaxDD, df_MedianReturn_MaxDD, df_CAGR_MaxDD, df_TreynorRatio, df_TreynorRatio_Annualized, df_SharpeRatio, df_SharpeRatio_Annualized, df_SortinoRatio, df_SortinoRatio_Annualized, df_CalmarRatio, df_CalmarRatio_Annualized, df_Gaussian_VaR, df_CornishFisher_VaR, df_Total_NumOfPeriods, df_Winning_AvgReturn, df_Winning_MedianReturn, df_Winning_MaxReturn, df_Winning_MinReturn, df_Winning_StDev, df_Winning_Variance, df_Winning_NumOfPeriods, df_WinningPerc, df_Losing_AvgReturn, df_Losing_MedianReturn, df_Losing_MaxReturn, df_Losing_MinReturn, df_Losing_StDev, df_Losing_Variance, df_Losing_NumOfPeriods, df_LosingPerc, df_Win_Loss_Ratio, df_Expectancy, df_ExepectancyRatio, df_Sum_of_Returns, df_Sum_of_Losses, df_Gain_to_Pain_Ratio, df_Sharpe_Ratio_Skew = RankingModel().metrics_dataframes(
# t_AvgReturn, t_MedianReturn, t_MaxReturn, t_MinReturn, t_StDev, t_Variance, t_Beta, t_DownsideDev, t_Skew, t_Kurtosis, t_Kurt_Skew, t_ExcessKurtosis, t_ExcessKurtosis_Skew, t_CompoundedReturn, t_CAGR, t_MaxDD, t_MarkowitzReturnFunction, t_MarkowitzReturnFunction_CAGR, t_AvgReturn_StDev, t_MedianReturn_StDev, t_CAGR_StDev, t_AvgReturn_MaxDD, t_MedianReturn_MaxDD, t_CAGR_MaxDD, t_TreynorRatio, t_TreynorRatio_Annualized, t_SharpeRatio, t_SharpeRatio_Annualized, t_SortinoRatio, t_SortinoRatio_Annualized, t_CalmarRatio, t_CalmarRatio_Annualized, t_Gaussian_VaR, t_CornishFisher_VaR, t_Total_NumOfPeriods, t_Winning_AvgReturn, t_Winning_MedianReturn, t_Winning_MaxReturn, t_Winning_MinReturn, t_Winning_StDev, t_Winning_Variance, t_Winning_NumOfPeriods, t_WinningPerc, t_Losing_AvgReturn, t_Losing_MedianReturn, t_Losing_MaxReturn, t_Losing_MinReturn, t_Losing_StDev, t_Losing_Variance, t_Losing_NumOfPeriods, t_LosingPerc, t_Win_Loss_Ratio, t_Expectancy, t_ExepectancyRatio, t_Sum_of_Returns, t_Sum_of_Losses, t_Gain_to_Pain_Ratio, t_Sharpe_Ratio_Skew = RankingModel().metrics_transposed()
RankingModel().ranking_model()